// File generated by Hermes Agent
package com.example.gymapp.presentation.trainer

import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.material3.TabRowDefaults.tabIndicatorOffset
import androidx.compose.runtime.*

import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.example.gymapp.domain.model.*
import com.example.gymapp.ui.theme.*
import com.example.gymapp.utils.DateUtils
import com.example.gymapp.presentation.components.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun StudentDetailScreen(
    studentId: String,
    viewModel: ProfessorViewModel,
    onBack: () -> Unit,
) {
    // Load data when the composable appears
    LaunchedEffect(studentId) {
        viewModel.loadStudentDetail(studentId)
        viewModel.loadInstitutos()
    }

    // Collect states from ViewModel
    val student by viewModel.selectedStudentDetail.collectAsState()
    val profile by viewModel.studentProfile.collectAsState()
    val measurements by viewModel.studentMeasurements.collectAsState()
    val studentExerciseCustomMetrics by viewModel.studentExerciseCustomMetrics.collectAsState()

    val sessions by viewModel.studentSessions.collectAsState()
    val stats by viewModel.studentStats.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val error by viewModel.error.collectAsState()
    // New: collect groups the student belongs to
    val studentGroups by viewModel.studentGroups.collectAsState()
    // Exercise progress
    val exerciseProgress by viewModel.studentExerciseProgress.collectAsState()
    val exerciseProgressLoading by viewModel.studentExerciseProgressLoading.collectAsState()
    val assignments by viewModel.studentAssignments.collectAsState()
    
    val institutos by viewModel.institutos.collectAsState()

    var selectedTabIndex by remember { mutableStateOf(0) }
    val tabs = listOf("Perfil", "Medições", "Treinos")
    
    var showChangeInstitutoDialog by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        val initials = student?.fullName?.split(" ")?.mapNotNull { it.firstOrNull()?.toString() }?.joinToString("") ?: "?"
                        Box(
                            modifier = Modifier
                                .size(40.dp)
                                .clip(CircleShape)
                                .background(
                                    Brush.linearGradient(
                                        colors = listOf(IfgGreen, MaterialTheme.colorScheme.primary)
                                    )
                                )
                        ) {
                            Text(
                                text = initials.uppercase(),
                                color = Color.White,
                                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                                modifier = Modifier.align(Alignment.Center)
                            )
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        Column {
                            Text(
                                text = student?.fullName ?: "Aluno",
                                maxLines = 1,
                                overflow = TextOverflow.Ellipsis,
                                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold)
                            )
                            val resolvedInstitutoName = student?.instituto?.ifBlank { null } 
                                ?: institutos.find { it.id == student?.institutoId }?.name 
                                ?: "Sem Instituto"
                            Text(
                                text = resolvedInstitutoName,
                                style = MaterialTheme.typography.labelSmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(imageVector = Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Voltar")
                    }
                },
                actions = {
                    IconButton(onClick = { showChangeInstitutoDialog = true }) {
                        Icon(imageVector = Icons.Default.Business, contentDescription = "Alterar Instituto", tint = MaterialTheme.colorScheme.primary)
                    }
                }
            )
        }
    ) { innerPadding ->
        Column(modifier = Modifier
            .fillMaxSize()
            .padding(innerPadding)) {
            if (isLoading) {
                LinearProgressIndicator(modifier = Modifier.fillMaxWidth(), color = MaterialTheme.colorScheme.primary)
                return@Column
            }
            error?.let { errMsg ->
                Surface(
                    color = Color(0xFFFDE8E8), // soft light red background
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.padding(16.dp).fillMaxWidth()
                ) {
                    Text(
                        text = errMsg,
                        color = Color(0xFF9B1C1C), // dark crimson text
                        modifier = Modifier.padding(12.dp),
                        style = MaterialTheme.typography.bodyMedium,
                        fontWeight = FontWeight.Medium
                    )
                }
            }
            TabRow(
                selectedTabIndex = selectedTabIndex,
                indicator = { tabPositions ->
                    TabRowDefaults.SecondaryIndicator(
                        Modifier.tabIndicatorOffset(tabPositions[selectedTabIndex]),
                        color = MaterialTheme.colorScheme.primary
                    )
                }
            ) {
                tabs.forEachIndexed { index, title ->
                    Tab(
                        selected = selectedTabIndex == index,
                        onClick = { selectedTabIndex = index },
                        text = { 
                            Text(
                                title, 
                                fontWeight = if (selectedTabIndex == index) FontWeight.Bold else FontWeight.Normal,
                                color = if (selectedTabIndex == index) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant
                            ) 
                        }
                    )
                }
            }
            // Animated content for tab switching
            AnimatedContent(targetState = selectedTabIndex, label = "TabSwitch") { targetIdx ->
                when (targetIdx) {
                    0 -> PerfilTab(
                        student = student,
                        profile = profile,
                        stats = stats,
                        groups = studentGroups,
                        onChangeInstitutoClick = { showChangeInstitutoDialog = true }
                    )
                    1 -> MedicoesTab(
                        measurements = measurements,
                        sessions = sessions,
                        assignments = assignments,
                        exerciseProgress = exerciseProgress,
                        exerciseProgressLoading = exerciseProgressLoading,
                        onLoadExerciseProgress = { exerciseIds ->
                            viewModel.loadStudentExerciseProgress(exerciseIds)
                        },
                        studentExerciseCustomMetrics = studentExerciseCustomMetrics,
                        onSetMetric = { exerciseId, metricType ->
                            viewModel.setExerciseMetric(exerciseId, metricType)
                        }
                    )
                    2 -> TreinosTab(assignments, sessions)
                }
            }
        }
    }

    if (showChangeInstitutoDialog) {
        ChangeInstitutoDialog(
            currentInstitutoId = student?.institutoId,
            institutos = institutos,
            onDismiss = { showChangeInstitutoDialog = false },
            onConfirm = { selectedId ->
                viewModel.updateStudentInstituto(studentId, selectedId)
                showChangeInstitutoDialog = false
            }
        )
    }
}

@Composable
private fun ChangeInstitutoDialog(
    currentInstitutoId: String?,
    institutos: List<Instituto>,
    onDismiss: () -> Unit,
    onConfirm: (String) -> Unit
) {
    var selectedId by remember { mutableStateOf(currentInstitutoId ?: "") }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Alterar Instituto", fontWeight = FontWeight.Bold) },
        text = {
            Column(
                modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Text("Selecione o novo instituto para o aluno:", style = MaterialTheme.typography.bodyMedium)
                
                if (institutos.isEmpty()) {
                    Text("Nenhum instituto disponível.", color = MaterialTheme.colorScheme.error)
                } else {
                    institutos.forEach { inst ->
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(8.dp))
                                .background(
                                    if (selectedId == inst.id) MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.5f)
                                    else Color.Transparent
                                )
                                .clickable { selectedId = inst.id }
                                .padding(12.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            RadioButton(
                                selected = selectedId == inst.id,
                                onClick = { selectedId = inst.id },
                                colors = RadioButtonDefaults.colors(selectedColor = MaterialTheme.colorScheme.primary)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(inst.name, style = MaterialTheme.typography.bodyMedium)
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = { onConfirm(selectedId) },
                enabled = selectedId.isNotBlank(),
                colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary),
                shape = RoundedCornerShape(8.dp)
            ) {
                Text("Confirmar", color = MaterialTheme.colorScheme.onPrimary)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancelar")
            }
        },
        shape = RoundedCornerShape(16.dp)
    )
}

@Composable
private fun PerfilTab(
    student: User?,
    profile: AlunoProfile?,
    stats: AlunoStats?,
    groups: List<StudentGroup>,
    onChangeInstitutoClick: () -> Unit
) {
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // Upper student visual details card
        item {
            Card(
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.2f))
            ) {
                Column(modifier = Modifier.padding(20.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.Top
                    ) {
                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = student?.fullName ?: "Nome desconhecido",
                                style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold)
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                text = student?.email ?: "",
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                        
                        IconButton(
                            onClick = onChangeInstitutoClick,
                            modifier = Modifier
                                .clip(CircleShape)
                                .background(MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.3f))
                        ) {
                            Icon(
                                imageVector = Icons.Default.Business,
                                contentDescription = "Trocar Instituto",
                                tint = MaterialTheme.colorScheme.primary
                            )
                        }
                    }
                    
                    Spacer(modifier = Modifier.height(16.dp))

                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        val role = student?.role?.replaceFirstChar { it.uppercase() } ?: "Aluno"
                        SuggestionChip(
                            onClick = {},
                            label = { Text(role) },
                            colors = SuggestionChipDefaults.suggestionChipColors(
                                containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.2f),
                                labelColor = MaterialTheme.colorScheme.primary
                            ),
                            border = BorderStroke(1.dp, MaterialTheme.colorScheme.primary.copy(alpha = 0.2f))
                        )
                        val status = if (student?.isActive == true) "Ativo" else "Inativo"
                        val statusColor = if (student?.isActive == true) IfgGreen else MaterialTheme.colorScheme.error
                        SuggestionChip(
                            onClick = {},
                            label = { Text(status) },
                            colors = SuggestionChipDefaults.suggestionChipColors(
                                containerColor = statusColor.copy(alpha = 0.15f),
                                labelColor = statusColor
                            ),
                            border = BorderStroke(1.dp, statusColor.copy(alpha = 0.2f))
                        )
                    }
                }
            }
        }

        // Physical details info card
        item {
            Card(
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.2f))
            ) {
                Column(modifier = Modifier.padding(20.dp)) {
                    Text(
                        text = "Dados Físicos",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.primary
                    )
                    Spacer(modifier = Modifier.height(16.dp))
                    
                    if (profile != null) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                Text(
                                    text = "${profile.currentWeightKg ?: "-"} kg",
                                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                                )
                                Text("Peso", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                            Box(modifier = Modifier.width(1.dp).height(40.dp).background(MaterialTheme.colorScheme.outlineVariant))
                            Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                Text(
                                    text = "${profile.heightCm ?: "-"} cm",
                                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                                )
                                Text("Altura", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                            Box(modifier = Modifier.width(1.dp).height(40.dp).background(MaterialTheme.colorScheme.outlineVariant))
                            
                            val bmi = if (profile.currentWeightKg != null && profile.heightCm != null && profile.heightCm > 0) {
                                val h = profile.heightCm / 100.0
                                String.format("%.1f", profile.currentWeightKg / (h * h))
                            } else "--"
                            
                            Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                Text(
                                    text = bmi,
                                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                                )
                                Text("IMC", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(20.dp))
                        Divider(color = MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.5f))
                        Spacer(modifier = Modifier.height(16.dp))
                        
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(imageVector = Icons.Default.Healing, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Text("Histórico de Lesões", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                Text(
                                    text = profile.injuryHistory ?: "Nenhum histórico de lesões registrado",
                                    style = MaterialTheme.typography.bodyLarge,
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }
                    } else {
                        Text(
                            text = "O aluno ainda não preencheu as informações do perfil.",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            modifier = Modifier.fillMaxWidth(),
                            textAlign = TextAlign.Center
                        )
                    }

                    // Groups sub-section
                    if (groups.isNotEmpty()) {
                        Spacer(modifier = Modifier.height(20.dp))
                        Divider(color = MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.5f))
                        Spacer(modifier = Modifier.height(16.dp))
                        
                        Text(
                            "Grupos",
                            style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.SemiBold),
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            groups.forEach { group ->
                                AssistChip(
                                    onClick = {},
                                    label = { Text(group.name) },
                                    colors = AssistChipDefaults.assistChipColors(
                                        containerColor = MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.3f),
                                        labelColor = MaterialTheme.colorScheme.onSecondaryContainer
                                    )
                                )
                            }
                        }
                    }
                }
            }
        }

        // Stats card (Sessões, Concluídas, Streak, Frequência)
        item {
            Card(
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.2f))
            ) {
                Column(modifier = Modifier.padding(20.dp)) {
                    Text(
                        text = "Estatísticas de Treino",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.primary
                    )
                    Spacer(modifier = Modifier.height(16.dp))
                    
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        StatItemCard(
                            label = "Sessões",
                            value = stats?.totalSessions?.toString() ?: "0",
                            icon = Icons.Default.FitnessCenter,
                            modifier = Modifier.weight(1f)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        StatItemCard(
                            label = "Concluídas",
                            value = stats?.completedSessions?.toString() ?: "0",
                            icon = Icons.Default.CheckCircle,
                            modifier = Modifier.weight(1f)
                        )
                    }
                    Spacer(modifier = Modifier.height(8.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        StatItemCard(
                            label = "Streak",
                            value = "${stats?.currentStreak ?: 0} dias",
                            icon = Icons.Default.LocalFireDepartment,
                            modifier = Modifier.weight(1f)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        StatItemCard(
                            label = "Frequência",
                            value = "${stats?.weeklyFrequency ?: 0.0}x/sem",
                            icon = Icons.Default.CalendarToday,
                            modifier = Modifier.weight(1f)
                        )
                    }
                }
            }
        }
    }
}

@Composable
private fun StatItemCard(
    label: String,
    value: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    modifier: Modifier = Modifier
) {
    Card(
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f)),
        modifier = modifier
    ) {
        Row(
            modifier = Modifier.padding(12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Box(
                modifier = Modifier
                    .size(36.dp)
                    .clip(CircleShape)
                    .background(MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.4f)),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    imageVector = icon,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.primary,
                    modifier = Modifier.size(18.dp)
                )
            }
            Spacer(modifier = Modifier.width(12.dp))
            Column {
                Text(
                    text = value,
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold)
                )
                Text(
                    text = label,
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
        }
    }
}


@Composable
private fun MedicoesTab(
    measurements: List<BodyMeasurement>,
    sessions: List<WorkoutSession>,
    assignments: List<WorkoutAssignment>,
    exerciseProgress: Map<String, List<ExerciseProgressPoint>>,
    exerciseProgressLoading: Boolean,
    onLoadExerciseProgress: (List<String>) -> Unit,
    studentExerciseCustomMetrics: Map<String, ExerciseCustomMetric> = emptyMap(),
    onSetMetric: (String, String) -> Unit = { _, _ -> }
) {
    // Date range filter state
    var weightDateRange by remember { mutableStateOf(DateRangeFilter.LAST_90) }

    // Load exercise progress once when this tab is first composed
    LaunchedEffect(assignments, sessions) {
        val exerciseIds = sessions
            .flatMap { it.exercises ?: emptyList() }
            .mapNotNull { it.exerciseId }
            .distinct()
        if (exerciseIds.isNotEmpty() && exerciseProgress.isEmpty()) {
            onLoadExerciseProgress(exerciseIds.take(10))
        }
    }

    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp)) {
        if (measurements.isEmpty()) {
            item {
                Text(text = "Nenhuma medição registrada", style = MaterialTheme.typography.bodyMedium)
            }
        } else {
            // ============ BODY WEIGHT CHART ============
            item {
                Text(
                    text = "Evolução do Peso",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold)
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            // Date range selector
            item {
                DateRangeSelector(
                    selectedRange = weightDateRange,
                    onRangeSelected = { weightDateRange = it }
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            // Weight chart
            item {
                val weightChartData = measurements
                    .toWeightChartData()
                    .filterByDateRange(weightDateRange)
                val latestWeight = weightChartData.lastOrNull()?.value
                val firstWeight = weightChartData.firstOrNull()?.value
                val weightChange = if (latestWeight != null && firstWeight != null) {
                    val diff = latestWeight - firstWeight
                    String.format("%+.1f kg", diff)
                } else null

                ProgressLineChart(
                    data = weightChartData,
                    title = if (weightChange != null) "Peso Corporal ($weightChange)" else "Peso Corporal",
                    valueLabel = "kg",
                    lineColor = MaterialTheme.colorScheme.primary
                )
                Spacer(modifier = Modifier.height(16.dp))
            }

            // ============ EXERCISE PROGRESS CHARTS ============
            if (exerciseProgress.isNotEmpty()) {
                item {
                    Text(
                        text = "Progresso dos Exercícios",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold)
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                }
            }

            if (exerciseProgressLoading) {
                item {
                    LinearProgressIndicator(modifier = Modifier.fillMaxWidth())
                    Spacer(modifier = Modifier.height(8.dp))
                }
            }

            // Build exercise name map from sessions
            val exerciseNameMap = sessions
                .flatMap { it.exercises ?: emptyList() }
                .associate { it.exerciseId to (it.exerciseName ?: it.exerciseId) }

            // Exercise progress charts
            items(exerciseProgress.entries.toList().take(6)) { (exerciseId, progressPoints) ->
                val exerciseName = exerciseNameMap[exerciseId] ?: exerciseId
                val weightData = progressPoints.toExerciseChartData { it.maxWeightKg?.toFloat() }
                val repData = progressPoints.toExerciseChartData { it.totalReps?.toFloat() }

                val selectedMetric = studentExerciseCustomMetrics[exerciseId]?.metricType ?: "weight"
                ExerciseProgressChart(
                    exerciseName = exerciseName,
                    progressPoints = weightData,
                    selectedMetric = selectedMetric,
                    onMetricChanged = { newMetric ->
                        onSetMetric(exerciseId, newMetric)
                    },
                    lineColor = MaterialTheme.colorScheme.primary
                )

                if (repData.isNotEmpty()) {
                    Spacer(modifier = Modifier.height(8.dp))
                    ExerciseProgressChart(
                        exerciseName = "$exerciseName — Reps",
                        progressPoints = repData,
                        selectedMetric = "reps",
                        onMetricChanged = { },
                        lineColor = Blue600
                    )
                }
                Spacer(modifier = Modifier.height(8.dp))
            }

            // ============ MEASUREMENT HISTORY LIST ============
            item {
                Text(
                    text = "Histórico de Medições",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold)
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            items(measurements.sortedByDescending { it.measuredAt }) { measurement ->
                Card(
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Text(text = DateUtils.formatIsoDate(measurement.measuredAt), style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Peso: ${measurement.weightKg} kg", style = MaterialTheme.typography.bodySmall)
                    }
                }
            }
        }
    }
}

@Composable
private fun TreinosTab(
    assignments: List<WorkoutAssignment>,
    sessions: List<WorkoutSession>
) {
    // State to track expanded session cards - outside LazyColumn
    var expandedSessions by remember { mutableStateOf<Set<String>>(emptySet()) }
    
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp)) {
        // Current assignment (first with startsAt <= today and no endsAt or endsAt >= today)
        val current = assignments.firstOrNull { a ->
            val now = java.time.LocalDate.now()
            val start = try { java.time.LocalDate.parse(a.startsAt) } catch (_: Exception) { null }
            val end = try { a.endsAt?.let { java.time.LocalDate.parse(it) } } catch (_: Exception) { null }
            start != null && !start.isAfter(now) && (end == null || !end.isBefore(now))
        }
        if (current != null) {
            item {
                Card(
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text(text = "Treino Atual", style = MaterialTheme.typography.titleMedium)
                        Text(text = "Modelo: ${current.templateName ?: "Desconhecido"}", style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Dia atual: Treino ${(current.currentWorkoutIndex ?: 0) + 1}", style = MaterialTheme.typography.bodySmall)
                        Text(text = "Início: ${DateUtils.formatIsoDate(current.startsAt)}", style = MaterialTheme.typography.bodySmall)
                        Text(text = "Fim: ${DateUtils.formatIsoDate(current.endsAt)}", style = MaterialTheme.typography.bodySmall)
                    }
                }
                Spacer(modifier = Modifier.height(12.dp))
            }
        }
        // All assignments list
        if (assignments.isNotEmpty()) {
            item { Text(text = "Todos os treinos", style = MaterialTheme.typography.titleMedium) }
            items(assignments) { assignment ->
                Card(
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Text(text = assignment.templateName ?: "Desconhecido", style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Período: ${DateUtils.formatIsoDate(assignment.startsAt)} – ${DateUtils.formatIsoDate(assignment.endsAt)}", style = MaterialTheme.typography.bodySmall)
                        val idx = assignment.currentWorkoutIndex ?: 0
                        Text(text = "Dia atual: Treino ${idx + 1}", style = MaterialTheme.typography.labelSmall, color = IfgGreen)
                    }
                }
            }
            item { Spacer(modifier = Modifier.height(12.dp)) }
        }
        // Session history – expandable cards with inline rating
        if (sessions.isNotEmpty()) {
            item { Text(text = "Histórico de sessões", style = MaterialTheme.typography.titleMedium) }
            items(sessions) { session ->
                val isExpanded = expandedSessions.contains(session.id)
                val hasRating = session.rating != null
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                        .clickable {
                            expandedSessions = if (isExpanded) expandedSessions - session.id else expandedSessions + session.id
                        },
                    colors = CardDefaults.cardColors(
                        containerColor = if (session.finishedAt != null) Green100 else MaterialTheme.colorScheme.surface
                    )
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column {
                                Text(text = DateUtils.formatIsoDate(session.startedAt), style = MaterialTheme.typography.bodyMedium)
                                Text(text = "Sessão #${session.sessionNumber}", style = MaterialTheme.typography.bodySmall)
                                if (!session.workoutName.isNullOrBlank()) {
                                    Text(text = session.workoutName, style = MaterialTheme.typography.labelSmall, color = IfgGreen)
                                }
                            }
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                if (hasRating) {
                                    Icon(Icons.Filled.Star, contentDescription = null, tint = Color(0xFFFFC107), modifier = Modifier.size(16.dp))
                                    Text("${session.rating}", style = MaterialTheme.typography.labelMedium)
                                    Spacer(modifier = Modifier.width(4.dp))
                                }
                                Text(
                                    text = if (session.finishedAt != null) "Concluída" else "Pendente",
                                    color = if (session.finishedAt != null) IfgGreen else Color(0xFFF44336),
                                    style = MaterialTheme.typography.bodySmall
                                )
                            }
                        }
                        // Show rating details if rated (always visible for rated sessions)
                        if (hasRating) {
                            Spacer(modifier = Modifier.height(4.dp))
                            Row {
                                repeat(session.rating ?: 0) {
                                    Icon(Icons.Filled.Star, contentDescription = null, tint = Color(0xFFFFC107), modifier = Modifier.size(14.dp))
                                }
                            }
                            session.feedbackText?.let { fb ->
                                if (fb.isNotBlank()) {
                                    Text(text = fb, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                }
                            }
                        }
                    }
                }
            }
        } else {
            item { Text(text = "Nenhum histórico de treinos encontrado", style = MaterialTheme.typography.bodySmall) }
        }
    }
}
