// File generated by Hermes Agent
package com.example.gymapp.presentation.trainer

import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Star
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.example.gymapp.domain.model.*
import com.example.gymapp.ui.theme.*
import com.example.gymapp.utils.DateUtils
import com.example.gymapp.presentation.components.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun StudentDetailScreen(
    studentId: String,
    viewModel: ProfessorViewModel,
    onBack: () -> Unit,
) {
    // Load data when the composable appears
    LaunchedEffect(studentId) {
        viewModel.loadStudentDetail(studentId)
    }

    // Collect states from ViewModel
    val student by viewModel.selectedStudentDetail.collectAsState()
    val profile by viewModel.studentProfile.collectAsState()
    val measurements by viewModel.studentMeasurements.collectAsState()
    val studentExerciseCustomMetrics by viewModel.studentExerciseCustomMetrics.collectAsState()

    val sessions by viewModel.studentSessions.collectAsState()
    val stats by viewModel.studentStats.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val error by viewModel.error.collectAsState()
    // New: collect groups the student belongs to
    val studentGroups by viewModel.studentGroups.collectAsState()
    // Exercise progress
    val exerciseProgress by viewModel.studentExerciseProgress.collectAsState()
    val exerciseProgressLoading by viewModel.studentExerciseProgressLoading.collectAsState()
    val assignments by viewModel.studentAssignments.collectAsState()

    var selectedTabIndex by remember { mutableStateOf(0) }
    // Removed Avaliações tab – now only three tabs
    val tabs = listOf("Perfil", "Medições", "Treinos")

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        // Avatar with initials
                        val initials = student?.fullName?.split(" ")?.mapNotNull { it.firstOrNull()?.toString() }?.joinToString("")
                            ?: "?"
                        Box(
                            modifier = Modifier
                                .size(40.dp)
                                .clip(CircleShape)
                                .background(IfgGreen)
                        ) {
                            Text(
                                text = initials.uppercase(),
                                color = Color.White,
                                style = MaterialTheme.typography.titleMedium,
                                modifier = Modifier.align(Alignment.Center)
                            )
                        }
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = student?.fullName ?: "Aluno",
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                            style = MaterialTheme.typography.titleMedium
                        )
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(imageVector = Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Voltar")
                    }
                }
            )
        }
    ) { innerPadding ->
        Column(modifier = Modifier
            .fillMaxSize()
            .padding(innerPadding)) {
            if (isLoading) {
                LinearProgressIndicator(modifier = Modifier.fillMaxWidth())
                return@Column
            }
            error?.let { errMsg ->
                Text(text = errMsg, color = Color.Red, modifier = Modifier.padding(8.dp))
            }
            TabRow(selectedTabIndex = selectedTabIndex) {
                tabs.forEachIndexed { index, title ->
                    Tab(
                        selected = selectedTabIndex == index,
                        onClick = { selectedTabIndex = index },
                        text = { Text(title) }
                    )
                }
            }
            // Animated content for tab switching
            AnimatedContent(targetState = selectedTabIndex) { targetIdx ->
                when (targetIdx) {
                    0 -> PerfilTab(student, profile, stats, studentGroups)
                    1 -> MedicoesTab(
                        measurements = measurements,
                        sessions = sessions,
                        assignments = assignments,
                        exerciseProgress = exerciseProgress,
                        exerciseProgressLoading = exerciseProgressLoading,
                        onLoadExerciseProgress = { exerciseIds ->
                            viewModel.loadStudentExerciseProgress(exerciseIds)
                        },
                        studentExerciseCustomMetrics = studentExerciseCustomMetrics,
                        onSetMetric = { exerciseId, metricType ->
                            viewModel.setExerciseMetric(exerciseId, metricType)
                        }
                    )
                    2 -> TreinosTab(assignments, sessions)
                }
            }
        }
    }
}

@Composable
private fun PerfilTab(
    student: User?,
    profile: AlunoProfile?,
    stats: AlunoStats?,
    groups: List<StudentGroup>
) {
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp)) {
        item {
            Card(
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(text = student?.fullName ?: "Nome desconhecido", style = MaterialTheme.typography.titleLarge)
                    Text(text = student?.email ?: "", style = MaterialTheme.typography.bodyMedium)
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        val role = student?.role?.replaceFirstChar { it.uppercase() } ?: "Aluno"
                        Badge(
                            containerColor = IfgGreen,
                            contentColor = Color.White,
                            modifier = Modifier.padding(end = 8.dp)
                        ) { Text(role) }
                        val status = if (student?.isActive == true) "Ativo" else "Inativo"
                        Badge(
                            containerColor = if (student?.isActive == true) Color(0xFF4CAF50) else Color(0xFFF44336),
                            contentColor = Color.White
                        ) { Text(status) }
                    }
                    Spacer(modifier = Modifier.height(8.dp))
                    profile?.let { p ->
                        Text(text = "Peso: ${p.currentWeightKg ?: "-"} kg", style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Altura: ${p.heightCm ?: "-"} cm", style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Lesões: ${p.injuryHistory ?: "Nenhuma"}", style = MaterialTheme.typography.bodyMedium)
                    } ?: run {
                        Text(text = "Aluno ainda não preencheu o perfil", style = MaterialTheme.typography.bodyMedium)
                    }
                    // Groups section
                    if (groups.isNotEmpty()) {
                        Spacer(modifier = Modifier.height(12.dp))
                        Text(
                            "Grupos",
                            style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.SemiBold)
                        )
                        groups.forEach { group ->
                            Badge(containerColor = Color(0xFFE3F2FD)) {
                                Text(
                                    group.name,
                                    color = Color(0xFF1565C0),
                                    style = MaterialTheme.typography.labelSmall
                                )
                            }
                        }
                    }
                }
            }
        }
        item {
            Spacer(modifier = Modifier.height(16.dp))
            Card(
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    StatItem(label = "Sessões", value = stats?.totalSessions?.toString() ?: "0")
                    StatItem(label = "Concluídas", value = stats?.completedSessions?.toString() ?: "0")
                    StatItem(label = "Streak", value = stats?.currentStreak?.toString() ?: "0")
                    StatItem(label = "Frequência", value = stats?.weeklyFrequency?.toString() ?: "0")
                }
            }
        }
    }
}

@Composable
private fun StatItem(label: String, value: String) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text(text = value, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
        Text(text = label, style = MaterialTheme.typography.bodySmall)
    }
}

@Composable
private fun MedicoesTab(
    measurements: List<BodyMeasurement>,
    sessions: List<WorkoutSession>,
    assignments: List<WorkoutAssignment>,
    exerciseProgress: Map<String, List<ExerciseProgressPoint>>,
    exerciseProgressLoading: Boolean,
    onLoadExerciseProgress: (List<String>) -> Unit,
    studentExerciseCustomMetrics: Map<String, ExerciseCustomMetric> = emptyMap(),
    onSetMetric: (String, String) -> Unit = { _, _ -> }
) {
    // Date range filter state
    var weightDateRange by remember { mutableStateOf(DateRangeFilter.LAST_90) }

    // Load exercise progress once when this tab is first composed
    LaunchedEffect(assignments, sessions) {
        val exerciseIds = sessions
            .flatMap { it.exercises ?: emptyList() }
            .mapNotNull { it.exerciseId }
            .distinct()
        if (exerciseIds.isNotEmpty() && exerciseProgress.isEmpty()) {
            onLoadExerciseProgress(exerciseIds.take(10))
        }
    }

    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp)) {
        if (measurements.isEmpty()) {
            item {
                Text(text = "Nenhuma medição registrada", style = MaterialTheme.typography.bodyMedium)
            }
        } else {
            // ============ BODY WEIGHT CHART ============
            item {
                Text(
                    text = "Evolução do Peso",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold)
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            // Date range selector
            item {
                DateRangeSelector(
                    selectedRange = weightDateRange,
                    onRangeSelected = { weightDateRange = it }
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            // Weight chart
            item {
                val weightChartData = measurements
                    .toWeightChartData()
                    .filterByDateRange(weightDateRange)
                val latestWeight = weightChartData.lastOrNull()?.value
                val firstWeight = weightChartData.firstOrNull()?.value
                val weightChange = if (latestWeight != null && firstWeight != null) {
                    val diff = latestWeight - firstWeight
                    String.format("%+.1f kg", diff)
                } else null

                ProgressLineChart(
                    data = weightChartData,
                    title = if (weightChange != null) "Peso Corporal ($weightChange)" else "Peso Corporal",
                    valueLabel = "kg",
                    lineColor = MaterialTheme.colorScheme.primary
                )
                Spacer(modifier = Modifier.height(16.dp))
            }

            // ============ EXERCISE PROGRESS CHARTS ============
            if (exerciseProgress.isNotEmpty()) {
                item {
                    Text(
                        text = "Progresso dos Exercícios",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold)
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                }
            }

            if (exerciseProgressLoading) {
                item {
                    LinearProgressIndicator(modifier = Modifier.fillMaxWidth())
                    Spacer(modifier = Modifier.height(8.dp))
                }
            }

            // Build exercise name map from sessions
            val exerciseNameMap = sessions
                .flatMap { it.exercises ?: emptyList() }
                .associate { it.exerciseId to (it.exerciseName ?: it.exerciseId) }

            // Exercise progress charts
            items(exerciseProgress.entries.toList().take(6)) { (exerciseId, progressPoints) ->
                val exerciseName = exerciseNameMap[exerciseId] ?: exerciseId
                val weightData = progressPoints.toExerciseChartData { it.maxWeightKg?.toFloat() }
                val repData = progressPoints.toExerciseChartData { it.totalReps?.toFloat() }

                val selectedMetric = studentExerciseCustomMetrics[exerciseId]?.metricType ?: "weight"
                ExerciseProgressChart(
                    exerciseName = exerciseName,
                    progressPoints = weightData,
                    selectedMetric = selectedMetric,
                    onMetricChanged = { newMetric ->
                        onSetMetric(exerciseId, newMetric)
                    },
                    lineColor = MaterialTheme.colorScheme.primary
                )

                if (repData.isNotEmpty()) {
                    Spacer(modifier = Modifier.height(8.dp))
                    ExerciseProgressChart(
                        exerciseName = "$exerciseName — Reps",
                        progressPoints = repData,
                        selectedMetric = "reps",
                        onMetricChanged = { },
                        lineColor = Blue600
                    )
                }
                Spacer(modifier = Modifier.height(8.dp))
            }

            // ============ MEASUREMENT HISTORY LIST ============
            item {
                Text(
                    text = "Histórico de Medições",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold)
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            items(measurements.sortedByDescending { it.measuredAt }) { measurement ->
                Card(
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Text(text = DateUtils.formatIsoDate(measurement.measuredAt), style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Peso: ${measurement.weightKg} kg", style = MaterialTheme.typography.bodySmall)
                        measurement.notes?.let { notes ->
                            Text(text = "Observação: $notes", style = MaterialTheme.typography.bodySmall)
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun TreinosTab(
    assignments: List<WorkoutAssignment>,
    sessions: List<WorkoutSession>
) {
    // State to track expanded session cards - outside LazyColumn
    var expandedSessions by remember { mutableStateOf<Set<String>>(emptySet()) }
    
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp)) {
        // Current assignment (first with startsAt <= today and no endsAt or endsAt >= today)
        val current = assignments.firstOrNull { a ->
            val now = java.time.LocalDate.now()
            val start = try { java.time.LocalDate.parse(a.startsAt) } catch (_: Exception) { null }
            val end = try { a.endsAt?.let { java.time.LocalDate.parse(it) } } catch (_: Exception) { null }
            start != null && !start.isAfter(now) && (end == null || !end.isBefore(now))
        }
        if (current != null) {
            item {
                Card(
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text(text = "Treino Atual", style = MaterialTheme.typography.titleMedium)
                        Text(text = "Modelo: ${current.templateName ?: "Desconhecido"}", style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Dia atual: Treino ${(current.currentWorkoutIndex ?: 0) + 1}", style = MaterialTheme.typography.bodySmall)
                        Text(text = "Início: ${DateUtils.formatIsoDate(current.startsAt)}", style = MaterialTheme.typography.bodySmall)
                        Text(text = "Fim: ${DateUtils.formatIsoDate(current.endsAt)}", style = MaterialTheme.typography.bodySmall)
                    }
                }
                Spacer(modifier = Modifier.height(12.dp))
            }
        }
        // All assignments list
        if (assignments.isNotEmpty()) {
            item { Text(text = "Todos os treinos", style = MaterialTheme.typography.titleMedium) }
            items(assignments) { assignment ->
                Card(
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Text(text = assignment.templateName ?: "Desconhecido", style = MaterialTheme.typography.bodyMedium)
                        Text(text = "Período: ${DateUtils.formatIsoDate(assignment.startsAt)} – ${DateUtils.formatIsoDate(assignment.endsAt)}", style = MaterialTheme.typography.bodySmall)
                        val idx = assignment.currentWorkoutIndex ?: 0
                        Text(text = "Dia atual: Treino ${idx + 1}", style = MaterialTheme.typography.labelSmall, color = IfgGreen)
                    }
                }
            }
            item { Spacer(modifier = Modifier.height(12.dp)) }
        }
        // Session history – expandable cards with inline rating
        if (sessions.isNotEmpty()) {
            item { Text(text = "Histórico de sessões", style = MaterialTheme.typography.titleMedium) }
            items(sessions) { session ->
                val isExpanded = expandedSessions.contains(session.id)
                val hasRating = session.rating != null
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                        .clickable {
                            expandedSessions = if (isExpanded) expandedSessions - session.id else expandedSessions + session.id
                        },
                    colors = CardDefaults.cardColors(
                        containerColor = if (session.finishedAt != null) Green100 else MaterialTheme.colorScheme.surface
                    )
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column {
                                Text(text = DateUtils.formatIsoDate(session.startedAt), style = MaterialTheme.typography.bodyMedium)
                                Text(text = "Sessão #${session.sessionNumber}", style = MaterialTheme.typography.bodySmall)
                                if (!session.workoutName.isNullOrBlank()) {
                                    Text(text = session.workoutName, style = MaterialTheme.typography.labelSmall, color = IfgGreen)
                                }
                            }
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                if (hasRating) {
                                    Icon(Icons.Filled.Star, contentDescription = null, tint = Color(0xFFFFC107), modifier = Modifier.size(16.dp))
                                    Text("${session.rating}", style = MaterialTheme.typography.labelMedium)
                                    Spacer(modifier = Modifier.width(4.dp))
                                }
                                Text(
                                    text = if (session.finishedAt != null) "Concluída" else "Pendente",
                                    color = if (session.finishedAt != null) IfgGreen else Color(0xFFF44336),
                                    style = MaterialTheme.typography.bodySmall
                                )
                            }
                        }
                        // Show rating details if rated (always visible for rated sessions)
                        if (hasRating) {
                            Spacer(modifier = Modifier.height(4.dp))
                            Row {
                                repeat(session.rating ?: 0) {
                                    Icon(Icons.Filled.Star, contentDescription = null, tint = Color(0xFFFFC107), modifier = Modifier.size(14.dp))
                                }
                            }
                            session.feedbackText?.let { fb ->
                                if (fb.isNotBlank()) {
                                    Text(text = fb, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                }
                            }
                        }
                    }
                }
            }
        } else {
            item { Text(text = "Nenhum histórico de treinos encontrado", style = MaterialTheme.typography.bodySmall) }
        }
    }
}
